
# 허깅페이스를 이용한 토크나이저와 엠베딩 기능 확인하기


# py39에서 실행

In [1]:
# 3 다음은 파일("/home/사용자아이디/.env")에 저장된 API_KEY 정보를 자동으로 읽어오는 기능

from dotenv import load_dotenv
load_dotenv("/home/mhkwon/.env")

import os

#HF_TOKEN = "get your token in http://hf.co/settings/tokens"
HF_TOKEN = os.getenv('HF_TOKEN')
print(HF_TOKEN)

from huggingface_hub import login
hf_token = login(token=HF_TOKEN, add_to_git_credential=True)

# 에러가 나면, linux에서 다음 명령어를 실행
# git config --global credential.helper store

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


Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.


In [2]:
import os
os.getcwd()

'/linuxhdd/mychatbot/my_note'

In [3]:

import torch

print(torch.__version__)

2.6.0.dev20241030+cu121


In [4]:
import transformers

print(transformers.__version__)

4.44.0


In [5]:
# 1) 표준 템플릿


#############################################################
# 0) 선언 부분

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# cpu/gpu를 선택 또는 지정
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#device = "cpu"
print('Using device:', device)

model_id = 'meta-llama/Llama-3.2-1B' # 
#model_id = 'LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct'
#model_id = 'naver-clova-ix/donut-base-finetuned-docvqa' # 에러 발생
#model_id = 'naver-clova-ix/donut-base-finetuned-cord-v2' # 에러 발생
#model_id = 'upstage/SOLAR-10.7B-v1.0'
#model_id = 'yanolja/EEVE-Korean-10.8B-v1.0'
#model_id = 'migtissera/Trinity-2-Codestral-22B-v0.2'
#model_id = 'BAAI/Infinity-Instruct-7M-Gen-Llama3_1-8B'


tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    #trust_remote_code=True,  # exaone only
)

#############################################################
# 1) prompt과정

# 결과값을 보여주는 template
if tokenizer.chat_template is None:
    tokenizer.chat_template = "{% for message in messages %}{% if message['role'] == 'user' %}{{ ' ' }}{% endif %}{{ message['content'] }}{% if not loop.last %}{{ '  ' }}{% endif %}{% endfor %}{{ eos_token }}"

instruction = "철수가 20개의 연필을 가지고 있었는데 영희가 절반을 가져가고, 민수가 남은 5개를 가져갔으면 철수에게 남은 연필의 갯수는 몇개인가요?"

messages = [
    {"role": "user", "content": f"{instruction}"}
    ]


#############################################################
# 2) tokenizer과정
input_ids = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    return_tensors="pt",
).to(model.device)

# 'unsloth/Llama-3.2-1B-Instruct 사용시에는 다음을 막아야 함.
#if model_id == 'meta-llama/Llama-3.2-1B':
#    model.generation_config.pad_token_id = model.generation_config.eos_token_id
#    model.generation_config.pad_token_id = tokenizer.pad_token_id   # 설정하지 않으면, 무한 CPU 실행

#if tokenizer.pad_token is None:
#    tokenizer.pad_token = tokenizer.eos_token
#if tokenizer.pad_token_id is None:
tokenizer.pad_token_id = tokenizer.eos_token_id

terminators = [
    tokenizer.eos_token_id,
    tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

#############################################################
# 3) LLM과정

# 실행시간을 측정하는 모듈
import time

start_time = time.time()
outputs = model.generate(
    input_ids,
    max_new_tokens=200,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
    #eos_token_id=terminators, 
    pad_token_id = tokenizer.eos_token_id,  # llama 3.2, bllossom
)
end_time = time.time()
print('elapsed time =', end_time - start_time)


#############################################################
# 4) decoder과정
answer = tokenizer.decode(outputs[0])

# 특수 토근을 제거하고, 출력
print(tokenizer.decode(outputs[0][input_ids.shape[-1]:], skip_special_tokens=True))

Using device: cuda


The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


elapsed time = 6.6991286277771
Question: 20개의 연필을 가지고 있었는데 영희가 절반을 가져가고, 민수가 남은 5개를 가져갔으면 철수에게 남은 연필의 갯수는 몇개인가요? A. 10 B. 15 C. 20 D. 25 E. 30
Answer: B


In [6]:
# 질의 문자열을 토큰으로 나투어서 숫자로 변환

encoded = tokenizer.encode(instruction)
encoded

[128000,
 107837,
 123503,
 220,
 508,
 123590,
 78453,
 110174,
 18359,
 120693,
 107417,
 103170,
 101603,
 105204,
 20565,
 110217,
 101738,
 18359,
 89946,
 20565,
 35495,
 11,
 107138,
 123503,
 102484,
 34804,
 220,
 20,
 117594,
 89946,
 14705,
 242,
 91040,
 112521,
 24140,
 102244,
 102484,
 34804,
 78453,
 110174,
 21028,
 17196,
 107,
 24140,
 16969,
 113156,
 60861,
 115372,
 36811,
 30]

In [4]:
# 숫자를 다시, 원문자(토큰)로 변환(복구)

import numpy

encoded_arr = numpy.array(encoded)
decoded = tokenizer.decode(encoded_arr)
decoded

'<|begin_of_text|>철수가 20개의 연필을 가지고 있었는데 영희가 절반을 가져가고, 민수가 남은 5개를 가져갔으면 철수에게 남은 연필의 갯수는 몇개인가요?'

In [21]:
tokenizer

PreTrainedTokenizerFast(name_or_path='meta-llama/Llama-3.2-1B', vocab_size=128000, model_max_length=131072, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|begin_of_text|>', 'eos_token': '<|end_of_text|>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	128000: AddedToken("<|begin_of_text|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128001: AddedToken("<|end_of_text|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128002: AddedToken("<|reserved_special_token_0|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128003: AddedToken("<|reserved_special_token_1|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128004: AddedToken("<|finetune_right_pad_id|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128005: AddedToken("<|reserved_special_token_2|>", rst

In [5]:
# 단순 질의 문자열을 prompt로 변환해서, 전달

messages

[{'role': 'user',
  'content': '철수가 20개의 연필을 가지고 있었는데 영희가 절반을 가져가고, 민수가 남은 5개를 가져갔으면 철수에게 남은 연필의 갯수는 몇개인가요?'}]

In [6]:
input_ids

tensor([[112521, 123503,    220,    508, 123590,  78453, 110174,  18359, 120693,
         107417, 103170, 101603, 105204,  20565, 110217, 101738,  18359,  89946,
          20565,  35495,     11, 107138, 123503, 102484,  34804,    220,     20,
         117594,  89946,  14705,    242,  91040, 112521,  24140, 102244, 102484,
          34804,  78453, 110174,  21028,  17196,    107,  24140,  16969, 113156,
          60861, 115372,  36811,     30, 128001]], device='cuda:0')

In [7]:
outputs

tensor([[112521, 123503,    220,    508, 123590,  78453, 110174,  18359, 120693,
         107417, 103170, 101603, 105204,  20565, 110217, 101738,  18359,  89946,
          20565,  35495,     11, 107138, 123503, 102484,  34804,    220,     20,
         117594,  89946,  14705,    242,  91040, 112521,  24140, 102244, 102484,
          34804,  78453, 110174,  21028,  17196,    107,  24140,  16969, 113156,
          60861, 115372,  36811,     30, 128001, 128000,  14924,    512,   3923,
            374,    279,  25655,   6928,   7698,    308,   1778,    430,    220,
             18,     61,     77,    374,  76016,    555,    220,     23,   5380,
          16533,    512,     17, 128001]], device='cuda:0')

In [8]:
answer

' 철수가 20개의 연필을 가지고 있었는데 영희가 절반을 가져가고, 민수가 남은 5개를 가져갔으면 철수에게 남은 연필의 갯수는 몇개인가요?<|end_of_text|><|begin_of_text|>Question:\nWhat is the smallest positive integer n such that 3^n is divisible by 8?\nAnswer:\n2<|end_of_text|>'

In [14]:
# Example text
text = "Love is wanting to be loved"

# Tokenize the text
input_ids = tokenizer.encode(text)
tokens = tokenizer.tokenize(tokenizer.decode(input_ids))

print("Input IDs:", input_ids)
print("-------" * 10)
print("Tokens:", tokens)

Input IDs: [128000, 29351, 374, 19762, 311, 387, 10456]
----------------------------------------------------------------------
Tokens: ['<|begin_of_text|>', 'Love', 'Ġis', 'Ġwanting', 'Ġto', 'Ġbe', 'Ġloved']


In [15]:
tokenizer(text)

{'input_ids': [128000, 29351, 374, 19762, 311, 387, 10456], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

In [7]:
model(input_ids)[0]

We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)


tensor([[[ 4.4062,  4.3125,  6.6875,  ..., -4.2812, -4.2812, -4.2812],
         [ 3.3906,  4.9375,  1.2188,  ..., -3.8594, -3.8594, -3.8594],
         [ 0.4961,  1.9219,  0.2793,  ...,  0.1143,  0.1138,  0.1138],
         ...,
         [10.2500, 10.8125,  5.1875,  ..., -1.9688, -1.9688, -1.9688],
         [ 3.3594,  4.2812,  6.0312,  ..., -4.0312, -4.0312, -4.0312],
         [ 1.4922, -2.5625,  0.9883,  ..., -1.3906, -1.3906, -1.3906]]],
       device='cuda:0', grad_fn=<ToCopyBackward0>)

In [8]:
model

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 2048)
    (layers): ModuleList(
      (0-15): 16 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (k_proj): Linear(in_features=2048, out_features=512, bias=False)
          (v_proj): Linear(in_features=2048, out_features=512, bias=False)
          (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=2048, out_features=8192, bias=False)
          (up_proj): Linear(in_features=2048, out_features=8192, bias=False)
          (down_proj): Linear(in_features=8192, out_features=2048, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
      )
    )
    (norm):

In [21]:
# llama 3.2버전

from transformers import AutoTokenizer, AutoModel
import torch

text = "Love is wanting to be loved"

model_id = 'meta-llama/Llama-3.2-1B'  # embedding vector size : 2048
#model_id = 'distilbert-base-uncased'

# Load pre-trained DistilBERT model
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id)

# Encode the tokens to obtain word embeddings
input_ids = tokenizer.encode(text, return_tensors='pt')
print("Input Text:", text)
print("Input IDs:", input_ids)

with torch.no_grad():
    word_embeddings = model(input_ids)[0]

print("Tensor Size:", word_embeddings.size())
print("------" * 10)
print("Word Embeddings:")
print(word_embeddings)


We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)


Input Text: Love is wanting to be loved
Input IDs: tensor([[128000,  29351,    374,  19762,    311,    387,  10456]])
Tensor Size: torch.Size([1, 7, 2048])
------------------------------------------------------------
Word Embeddings:
tensor([[[ 1.5497, -1.5041,  2.7454,  ..., -0.6332,  0.6005, -1.0105],
         [ 1.8866,  3.7083,  3.2908,  ..., -4.8652, -3.1015,  1.2896],
         [ 0.9821,  4.7516,  1.2729,  ..., -3.8063, -4.4535, -1.9424],
         ...,
         [-0.6961,  4.4318,  1.5390,  ..., -4.3151, -1.1161, -1.8278],
         [-0.3625,  4.5139,  0.2494,  ..., -3.8282, -4.2110, -1.4931],
         [ 0.6168,  4.4970,  1.4947,  ..., -2.5588, -3.3725, -0.1680]]])


In [2]:
#  llama 2버전

from transformers import AutoTokenizer, AutoModel
import torch

text = "Love is wanting to be loved"

model_id = 'meta-llama/llama-2-7b-hf'  # embedding vector size : 4096
#model_id = 'distilbert-base-uncased'

# Load pre-trained DistilBERT model
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id)

# Encode the tokens to obtain word embeddings
input_ids = tokenizer.encode(text, return_tensors='pt')
print("Input Text:", text)
print("Input IDs:", input_ids)

with torch.no_grad():
    word_embeddings = model(input_ids)[0]

print("Tensor Size:", word_embeddings.size())
print("------" * 10)
print("Word Embeddings:")
print(word_embeddings)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)


Input Text: Love is wanting to be loved
Input IDs: tensor([[    1,  8155,   338, 24507,   304,   367, 18012]])
Tensor Size: torch.Size([1, 7, 4096])
------------------------------------------------------------
Word Embeddings:
tensor([[[ 0.0153,  1.1657,  2.2452,  ...,  0.8615, -0.6877,  1.2167],
         [-1.6060,  0.8181, -1.8580,  ..., -0.3785,  1.5956,  1.4271],
         [ 2.4513, -2.3677,  1.2750,  ..., -2.5328, -0.0165, -1.7399],
         ...,
         [ 2.0222, -3.4781, -3.2751,  ..., -0.7063, -1.4323, -0.1302],
         [ 2.8371,  0.0147,  1.2894,  ..., -1.5004, -1.9146,  0.0913],
         [ 2.0618, -0.6372,  0.4139,  ..., -0.8831,  0.9339,  0.6793]]])


In [3]:
#  bert 버전

from transformers import AutoTokenizer, AutoModel
import torch

text = "Love is wanting to be loved"


#model_id = 'meta-llama/llama-2-7b-hf'  
model_id = 'distilbert-base-uncased'  # embedding vector size : 768

# Load pre-trained DistilBERT model
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id)

# Encode the tokens to obtain word embeddings
input_ids = tokenizer.encode(text, return_tensors='pt')
print("Input Text:", text)
print("Input IDs:", input_ids)

with torch.no_grad():
    word_embeddings = model(input_ids)[0]

print("Tensor Size:", word_embeddings.size())
print("------" * 10)
print("Word Embeddings:")
print(word_embeddings)

/home/mhkwon/anaconda3/envs/mychatbot/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


Input Text: Love is wanting to be loved
Input IDs: tensor([[ 101, 2293, 2003, 5782, 2000, 2022, 3866,  102]])
Tensor Size: torch.Size([1, 8, 768])
------------------------------------------------------------
Word Embeddings:
tensor([[[-0.1067, -0.0101, -0.0897,  ..., -0.1721,  0.2134,  0.3274],
         [ 0.8698,  0.1002,  0.2687,  ..., -0.3276,  0.4205,  0.1344],
         [-0.1877, -0.0777,  0.1905,  ..., -0.0220,  0.0024,  0.5138],
         ...,
         [ 0.5998, -0.2141,  0.3774,  ..., -0.3945, -0.1149,  0.1245],
         [ 1.1550, -0.1050,  0.3570,  ..., -0.4063, -0.0489, -0.0717],
         [ 1.0036,  0.1886, -0.4508,  ...,  0.0999, -0.5486, -0.3076]]])


In [1]:


# ***model_id에서 대소문자 구별하지 않으면서 huggingface에서 읽어오지만, 서버에 저장될때에는 대소문자 구분한다.

from transformers import AutoTokenizer, AutoModel
import torch

text = "Love is wanting to be loved"


#model_id = 'nvidia/Llama3-ChatQA-1.5-70B' # embedding vector size : 768
# 70B, 크기가 커서 CPU에 load (256GB로 늘린다음 최초 실행-실패다.), 20241102

# 'models--nvidia--Llama3-ChatQA-1.5-8B'
model_id = 'nvidia/Llama3-ChatQA-1.5-8B'

# Load pre-trained DistilBERT model
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id)

# Encode the tokens to obtain word embeddings
input_ids = tokenizer.encode(text, return_tensors='pt')
print("Input Text:", text)
print("Input IDs:", input_ids)

with torch.no_grad():
    word_embeddings = model(input_ids)[0]

print("Tensor Size:", word_embeddings.size())
print("------" * 10)
print("Word Embeddings:")
print(word_embeddings)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)


Input Text: Love is wanting to be loved
Input IDs: tensor([[29351,   374, 19762,   311,   387, 10456]])
Tensor Size: torch.Size([1, 6, 4096])
------------------------------------------------------------
Word Embeddings:
tensor([[[ 1.3966,  0.2266, -0.0617,  ...,  0.0185,  0.0289, -0.4262],
         [ 1.8441, -0.3517, -3.5521,  ...,  0.6562,  1.6911, -1.0170],
         [-2.1400, -1.3407, -2.1983,  ..., -1.2722,  3.3413, -3.1687],
         [-4.3804,  0.9260, -0.4428,  ...,  1.0083,  1.3176,  2.8172],
         [-0.2166, -0.1379, -3.7247,  ..., -1.9180,  0.1569,  1.1681],
         [ 0.7522, -1.9738, -1.3607,  ...,  0.3631,  1.5244, -2.3178]]])
